### ISSUE TITLE
serialport Fehler sobald der Cul Aktiv werden soll

### ISSUE THREAD

**Issue by Cupra-Bo** [ioBroker/ioBroker.maxcul#46]
Hallo, nachdem ich den Stick (der in Fhem ohne probleme ging) per "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A94xxxxx-if00-port0" einhänge und dann den Adapter Starte Blinkt der Adapter zwischen Rot und Gelb und im Log ist das hier zu sehen.

```
maxcul.0	2020-05-09 23:07:15.309	error	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
maxcul.0	2020-05-09 23:07:15.309	error	at Module._compile (internal/modules/cjs/loader.js:1133:30)
maxcul.0	2020-05-09 23:07:15.309	error	at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22)
maxcul.0	2020-05-09 23:07:15.309	error	at require (internal/modules/cjs/helpers.js:77:18)
maxcul.0	2020-05-09 23:07:15.309	error	at Module.require (internal/modules/cjs/loader.js:1019:19)
maxcul.0	2020-05-09 23:07:15.309	error	at Function.Module._load (internal/modules/cjs/loader.js:877:14)
maxcul.0	2020-05-09 23:07:15.309	error	at Module.load (internal/modules/cjs/loader.js:977:32)
maxcul.0	2020-05-09 23:07:15.309	error	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
maxcul.0	2020-05-09 23:07:15.309	error	at Module._compile (internal/modules/cjs/loader.js:1133:30)
maxcul.0	2020-05-09 23:07:15.309	error	at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:1:36)
maxcul.0	2020-05-09 23:07:15.309	error	at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48)
maxcul.0	2020-05-09 23:07:15.309	error	at require (internal/modules/cjs/helpers.js:77:18)
maxcul.0	2020-05-09 23:07:15.309	error	at Module.require (internal/modules/cjs/loader.js:1019:19)
maxcul.0	2020-05-09 23:07:15.309	error	at Function.Module._load (internal/modules/cjs/loader.js:877:14)
maxcul.0	2020-05-09 23:07:15.309	error	at Module.load (internal/modules/cjs/loader.js:977:32)
maxcul.0	2020-05-09 23:07:15.309	error	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1183:18)
maxcul.0	2020-05-09 23:07:15.309	error	(1873) Error: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
maxcul.0	2020-05-09 23:07:15.309	error	(1873) uncaught exception: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
maxcul.0	2020-05-09 23:07:15.245	info	(1873) starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.maxcul, node: v12.16.3
host.iobroker	2020-05-09 23:07:14.157	info	instance system.adapter.maxcul.0 started with pid 1873
host.iobroker	2020-05-09 23:07:14.151	info	"system.adapter.maxcul.0" enabled
```

**Comment by Apollon77** [comment]
The serialport installation was noft successfull it seems. Please execute "npm install --production" in "/opt/iobroker/node_modules/iobroker.maxcul"

**Comment by Apollon77** [comment]
Check 1.3.0 on GitHub please
