### ISSUE TITLE
kein SerialPort mehr zur auswahl

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.maxcul#47]
Hi,

ich hatte immer den Fehler : maxcul.0 (31492) unhandled promise rejection: undefined
und wollte dann wieder auf die 1.2.0 
die lies sich nicht installieren und bin wieder auf die 1.3.0
Leider zeigt er wir keine Serial Port mehr an

JS Controller 3.1.4
Node.js: v10.20.1
NPM: v6.14.4

`

2020-05-18 20:32:35.037  - warn: maxcul.0 (4940) Please define the serial port.
--
2020-05-18 20:32:35.374  - info: host.raspberrypi iobroker exit 0
2020-05-18 20:32:37.352  - info: host.raspberrypi instance system.adapter.maxcul.1 started with pid 5098
2020-05-18 20:32:39.101  - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-05-18 20:32:39.102  - error: maxcul.0 (4940) unhandled promise rejection: SerialPort.list no longer takes a callback and only returns a promise
2020-05-18 20:32:39.133  - error: maxcul.0 (4940) TypeError: SerialPort.list no longer takes a callback and only returns a promise
at Function.SerialPort.list (/opt/iobroker/node_modules/@serialport/stream/lib/index.js:651:11)
at Adapter.adapter.on.obj (/opt/iobroker/node_modules/iobroker.maxcul/main.js:147:40)
at Adapter.emit (events.js:198:13)
at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5313:34)
at Immediate.setImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:234:41)
at runCallback (timers.js:705:18)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
2020-05-18 20:32:39.185  - info: maxcul.0 (4940) terminating
2020-05-18 20:32:39.188  - info: maxcul.0 (4940) Terminated (NO_ERROR): Without reason
2020-05-18 20:32:39.720  - info: host.raspberrypi instance system.adapter.maxcul.0 terminated with code 0 (NO_ERROR)
2020-05-18 20:32:39.721  - info: host.raspberrypi Restart adapter system.adapter.maxcul.0 because enabled
2020-05-18 20:32:40.659  - info: maxcul.1 (5098) starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.maxcul, node: v10.20.1, js-controller: 3.1.4
2020-05-18 20:32:40.816  - warn: maxcul.1 (5098) Please define the serial port.

![Anmerkung 2020-05-18 203320](https://user-images.githubusercontent.com/61965330/82247731-30e0fb80-9947-11ea-9a6e-eeba25d01b68.jpg)
`

**Comment by Apollon77** [comment]
Hast du per Zufall auch nodejs aktualisiert?

**Comment by hoepps2802** [comment]
ja gestern, von 10 auf 12,

bin aber auch wieder zurück da Probleme mit anderem Adapter

**Comment by hoepps2802** [comment]
bin jetzt auch wieder auf JS Controller 2.2.9 gegangen.
maxcul ver 1.2.0 ist scheinbar nicht mehr verfügbar?!?
bin dann auf die maxcul 1.1.2 gegangen, Serial port wieder da
dann auf die 1.3.0 Port ist nicht mehr anwählbar, läuft aber da unter 1.1.2 konfiguriert

**Comment by D3ltorohd** [comment]
Habe auch Probleme, seitdem ich die neusten node und controller Updates gemacht habe. 
Den Port kann man wählen, wenn der Adapter gestoppt ist, so wars bei mir meine ich. Wenn er läuft wird bei mir auch nichts angezeigt.

**Comment by hoepps2802** [comment]
hab es so gemacht und funktionierte , Danke :-)
