### ISSUE TITLE
Nach update auf node.js 16.15.1 fehler

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.maxcul#61]
Nach dem Update auf Node.js 16.15.1 und npm 8.11.0 auf js-controller 4.0.23 kommt folgender Fehler:
`

2022-06-19 14:07:33.447  - error: host.iob Caught by controller[0]: Cannot load serialport module
--
2022-06-19 14:07:33.449  - error: host.iob instance system.adapter.maxcul.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-06-19 14:08:05.863  - error:  maxcul.0 (4677) uncaught exception: Module did not self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
2022-06-19 14:08:05.866  - error:  maxcul.0 (4677) Error: Module did not self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48)
at Object. (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:2:36)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22)
at Module._compile (node:internal/modules/cjs/loader:1105:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-06-19 14:08:05.866  - error:  maxcul.0 (4677) Exception-Code: ERR_DLOPEN_FAILED: Module did not  self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.

`

**Comment by Apollon77** [comment]
Seems that you need to recompile serialport after the modejs upgrade

cd /opt/iobroker/node_modules/@serialport/bindings
npm install

should fix it

**Comment by guergen1** [comment]
Perfekt!
Danke!
