### ISSUE TITLE
Der Adapter läuft nicht unter Node 18.x.x

### ISSUE THREAD

**Issue by Menne01** [ioBroker/ioBroker.maxcul#63]
Hi,
Iobroker ist auf dem letzten Beta Stand.
Habe gerade das System auf Node 18.16.1  geupgradet.

Maxcul startet nicht mehr.

Hier das Debug Log:

`
2023-07-15 14:54:52.459  - debug: maxcul.0 (9404) Redis Objects: Use Redis connection: 127.0.0.1:9001
--
2023-07-15 14:54:52.578  - debug: maxcul.0 (9404) Objects client ready ... initialize now
2023-07-15 14:54:52.625  - debug: maxcul.0 (9404) Objects create System PubSub Client
2023-07-15 14:54:52.628  - debug: maxcul.0 (9404) Objects create User PubSub Client
2023-07-15 14:54:52.804  - debug: maxcul.0 (9404) Objects client initialize lua scripts
2023-07-15 14:54:52.823  - debug: maxcul.0 (9404) Objects connected to redis: 127.0.0.1:9001
2023-07-15 14:54:52.956  - debug: maxcul.0 (9404) Redis States: Use Redis connection: 127.0.0.1:9000
2023-07-15 14:54:53.049  - debug: maxcul.0 (9404) States create System PubSub Client
2023-07-15 14:54:53.051  - debug: maxcul.0 (9404) States create User PubSub Client
2023-07-15 14:54:53.223  - debug: maxcul.0 (9404) States connected to redis: 127.0.0.1:9000
2023-07-15 14:54:54.359  - info: maxcul.0 (9404) starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.maxcul, node: v18.16.1, js-controller: 5.0.7
2023-07-15 14:54:55.055  - error:  maxcul.0 (9404) uncaught exception: Module did not self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
2023-07-15 14:54:55.056  - error:  maxcul.0 (9404) Error: Module did not self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:110:18)
at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48)
at Object. (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:2:36)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at Module.require (node:internal/modules/cjs/loader:1143:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object. (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22)
at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
2023-07-15 14:54:55.057  - error:  maxcul.0 (9404) Exception-Code: ERR_DLOPEN_FAILED: Module did not  self-register:  '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
2023-07-15 14:54:55.066  - info: maxcul.0 (9404) terminating
2023-07-15 14:54:55.079  - warn: maxcul.0 (9404) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-15 14:54:55.581  - info: maxcul.0 (9404) terminating
2023-07-15 14:54:55.776  - error: host.iobroker Caught by controller[0]: Cannot load serialport module
2023-07-15 14:54:55.781  - error: host.iobroker instance system.adapter.maxcul.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`
Grüße

**Comment by Menne01** [comment]
Erledigt.
