### ISSUE TITLE
Node.js20: Error: Module did not self-register

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.maxcul#64]
Adapter-Version: 1.3.1
JS-Controller: 5.0.19
Node.js : 20.13.1
NPM: 10.5.2
Debian als VM in Proxmox

Habe mal testweise auf nodejs20 hochgezogen.
Die serielle Schnittstelle kann nicht angesprochen werden.

Folgende Fehlermeldung kommt:
`Error: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'. at Module._extensions..node (node:internal/modules/cjs/loader:1454:18) at Module.load (node:internal/modules/cjs/loader:1208:32) at Module._load (node:internal/modules/cjs/loader:1024:12) at Module.require (node:internal/modules/cjs/loader:1233:19) at require (node:internal/modules/helpers:179:18) at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48) at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:2:36) at Module._compile (node:internal/modules/cjs/loader:1358:14) at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) at Module.load (node:internal/modules/cjs/loader:1208:32) at Module._load (node:internal/modules/cjs/loader:1024:12) at Module.require (node:internal/modules/cjs/loader:1233:19) at require (node:internal/modules/helpers:179:18) at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22) at Module._compile (node:internal/modules/cjs/loader:1358:14) at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)`

auch vom host.iob kommt eine Meldung:
`host.iob | 2024-05-25 18:15:34.658 | error | instance system.adapter.maxcul.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
host.iob | 2024-05-25 18:15:34.658 | error | Caught by controller[0]: Cannot load serialport module`

**Comment by Apollon77** [comment]
In fact serialport needs an update

**Comment by guergen1** [comment]
It works fine

**Comment by guergen1** [comment]
Das hat genau einen Tag funktioniert, danach hat der maxcul-Adapter sich wieder gemeldet mit der slben Message. Was hab ich gemacht:
In den Ordner `/opt/iobroker/node_modules/serialport/` gewechselt und `npm install --production` ausgeführt.
Der Rechner gibt mir folgenden Hinweis:
`npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm WARN deprecated gauge@2.7.4: This package is no longer supported.

added 71 packages, and audited 74 packages in 12s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities`

Das läuft dann ein paar Tage und dann darf ich das wiederholen! 
Ich weiss, es hat nicht wirklich was mit maxcul zu tun, aber was ist dafür verantwortlich?
Issue bei NPM aufmachen? Oder wo sonst?

**Comment by Apollon77** [comment]
M< info stay s the same. Serialport needs an update in the adapter. I will do when I find time

**Comment by Menne01** [comment]
Geht es denn hier weiter?
Ich möchte den Node auf 20.x.x hochziehen.

**Comment by mcm1957** [comment]
@Apollon77 FYI / Reminder
